### ISSUE TITLE
Not Ruby way

### ISSUE THREAD

**Issue by Tonkonozhenko** [plekhotkindmytro/Factorial-for-Ruby#1]
Hi

The best way to calculate factorial in Ruby is

```
def factorial(n)
  (1..n).inject(:*)
end
```

or more explicit

```
def factorial(n)
   (1..n).inject(1) {|total, num| total *= num}
end
```

Try not to think in Java :smile:

**Comment by plekhotkindmytro** [comment]
Wow, 
thank you very much for knowledge sharing :+1:

**Comment by plekhotkindmytro** [comment]
I did not know that all ruby functions return result implicitly. Thanks :)
